---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - include_vars: "{{inventory_dir}}/host_vars/{{inventory_hostname_short}}.yml"
  - include_vars: "{{inventory_dir}}/group_vars/all.yml"    

  - name: Generated IOS configurations
    template: src=Generate-Configurations.j2 dest=configurations/{{inventory_hostname_short}}.cfg

  - name: Add Loopback Interfaces to configuration Files
    blockinfile: 
      dest: ./configurations/{{inventory_hostname_short}}.cfg
      marker: ""
      block: |
        interface Loopback 0
        ipv4 address {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}}  255.255.255.255
    when: ansible_os == "XR"

  - name: Add IOS Loopback Interfaces to configuration Files
    blockinfile: 
      dest: ./configurations/{{inventory_hostname_short}}.cfg
      marker: ""
      block: |
        interface Loopback 0
        ip address {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}}  255.255.255.255
    when: ansible_os == "IOS"        

  - name: Add Banner to configuration Files
    blockinfile: 
      dest: ./configurations/{{inventory_hostname_short}}.cfg
      marker: "! {mark} adding banners {{ nodeid }}"
      block: |
        banner login
        This configuration was generated by ansible for node {{nodeid}}. 

  - name: Add IOS Interfaces to configuration Files
    blockinfile: 
      dest: ./configurations/{{inventory_hostname_short}}.cfg
      marker: ""
      block: |
         interface {{item.port}}
          ip address {{item.ip}} {{item.mask}}
          description {{item.description}}
          ip ospf network point-to-point
          ip ospf 10 area 0
          duplex auto
          speed auto
          media-type rj45
    with_items: "{{ links }}"
    when: ansible_os == "IOS"

  - name: Add XR Interfaces to configuration Files
    blockinfile: 
      dest: ./configurations/{{inventory_hostname_short}}.cfg
      marker: ""
      block: |
         interface {{item.port}}
          ipv4 address {{item.ip}} {{item.mask}}
          description {{item.description}}
    with_items: "{{ links }}"
    when: ansible_os == "XR"


...