---
- hosts: all
  gather_facts: no
  connection: local
  tasks:

  - name: Delete Assemble directory
    file:
      path: ./configurations/assemble
      state: absent
      mode: '0755'
    run_once: True

  - name: Create Assemble directory
    file:
      path: ./configurations/assemble
      state: directory
      mode: '0755'
    run_once: True

    
##<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>#
- hosts: west
  gather_facts: no
  connection: local
  tasks:
  - include_vars: "{{inventory_dir}}/host_vars/{{inventory_hostname_short}}.yml"
  - include_vars: "services.yml"

  - name: Add IOS Loopback Interface fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/20_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
        interface Loopback 0
        ip address {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}}  255.255.255.255

  - name: Add IOS SNMP configuration fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/980_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         ip access-list standard NMS-STATIONS
          permit {{NMS1}}
          permit {{NMS2}}
         !
         snmp-server community public RO NMS-STATIONS
         snmp-server community private RW NMS-STATIONS
         snmp-server chassis-id 
         snmp-server host {{SNMP1}} version 2c public 
         snmp-server host {{SNMP2}} version 2c public 

  - name: Add IOS Interfaces fragments
    blockinfile: 
      create: yes
      dest: ./configurations/assemble/40_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         interface {{link.port}}
          ip address {{link.ip}} {{link.mask}}
          description {{link.description}}
          ip ospf network point-to-point
          ip ospf 10 area 0
          duplex auto
          speed auto
          media-type rj45
          !
    loop: "{{ links }}"
    loop_control:
      loop_var: link
      label: "Iteration {{count}} Adding {{link.description}}"     
      index_var: count

  - name: Add IOS Routing fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/50_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         router ospf 10
          router-id {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}}
          default-metric 1000
          network {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}} 0.0.0.0 area 0

  
#<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>#

- hosts: east
  gather_facts: no
  connection: local
  tasks:
  - include_vars: "{{inventory_dir}}/host_vars/{{inventory_hostname_short}}.yml"
  - include_vars: "services.yml"

  - name: Add XR Loopback Interfaces fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/60_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
        interface Loopback 0
        ipv4 address {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}}  255.255.255.255

  - name: Add XR SNMP fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/70_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         snmp-server host {{SNMP1}} traps version 2c public
         snmp-server host {{SNMP2}} traps version 2c public
         snmp-server community public RO IPv4 NMS-STATIONS
         snmp-server community private RW IPv4 NMS-STATIONS
         !
         ipv4 access-list NMS-STATIONS
          10 permit ipv4 host {{NMS1}} any
          20 permit ipv4 host {{NMS2}} any

  - name: Add XR Interfaces fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/80_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         interface {{link.port}}
          ipv4 address {{link.ip}} {{link.mask}}
          description {{link.description}}
          !
    loop: "{{ links }}"
    loop_control:
      loop_var: link
      label: "Adding physical interface {{link.port}}" 
      index_var: count      

  - name: Add XR routing fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/90_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         router ospf 10
          router-id {{( loopbacks | ipaddr (nodeid) | ipaddr ('address') )}}
          default-metric 1000
          area 0
           loopback stub-network enable
           interface Loopback 0
          !

  - name: Add XR Routed Interface fragments
    blockinfile:
      create: yes 
      dest: ./configurations/assemble/997_{{inventory_hostname_short}}.frg
      marker: ""
      block: |3
           interface {{link.port}}
           network point-to-point
           !
    loop: "{{ links }}"
    loop_control:
      loop_var: link
      label: "Adding routed interface {{link.port}}" 
      index_var: count     

#<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>#

- hosts: all
  gather_facts: no
  connection: local
  tasks:

  - name: Add users fragments
    blockinfile: 
      create: yes
      dest: ./configurations/assemble/10_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
         username {{user.username}} password 0 {{user.password}}
    loop: "{{ Users }}"
    loop_control:
      loop_var: user
      label: Adding {{user.username}} from group {{group_names}}

  - name: Add Banner fragments
    blockinfile: 
      create: yes
      dest: ./configurations/assemble/999_{{inventory_hostname_short}}.frg
      marker: ""
      block: |
        banner login
        This configuration was generated by ansible for node {{nodeid}}.

  - name: get status of files
    stat: path=configurations/{{inventory_hostname_short}}.cfg
#    loop: "{{inventory_hostname_short}}.cfg"
#    loop_control:
#      loop_var: host
#      label: "Makining checking for {{host}}.cfg" 
    register: CFG_STATUS
  
  - name: Rename the file to create backup and prevent appending
#    command: mv configurations/{{inventory_hostname_short}}.cfg configurations/{{inventory_hostname_short}}.bkup
    command: echo {{CFG_STATUS.stat}}  sort {{CFG_STATUS}}
    when: CFG_STATUS.stat.exists
 #   loop: "{{inventory_hostname_short}}.cfg"
 #   loop_control:
 #     loop_var: host
 #     label: "Makining back up of {{host}}.cfg" 


  - name: Assemble configuration fragments into an infra configuration
    assemble:
       src: ./configurations/assemble/
       dest: ./configurations/{{inventory_hostname_short}}.infra
       regexp: "{{inventory_hostname_short}}"
       delimiter: "!\n!" 

  - name: Assemble infra and services into a full configuration
    assemble:
       src: ./configurations/
       dest: ./configurations/{{inventory_hostname_short}}.cfg
       regexp: "{{inventory_hostname_short}}"
       delimiter: "!\n!"                       

  - name: Remove blank lines caused by loops from configurations
    replace:
      path: ./configurations/{{inventory_hostname_short}}.cfg
      regexp: "(^\n)"
      replace: ""     
...