---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - include_vars: "{{inventory_dir}}/hosts.yml"
  - include_vars: "{{inventory_dir}}/host_vars/{{inventory_hostname_short}}.yml"
  - include_vars: "services.yml"
  - name: Generated IOS configurations
    template: src=Generate-Services.j2 dest=configurations/{{inventory_hostname_short}}.services


 