---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - include_vars: "{{inventory_dir}}/host_vars/{{inventory_hostname_short}}.yml"
  - name: Generated IOS configurations
    template: src=Generate-Configurations.j2 dest=configurations/{{inventory_hostname_short}}.cfg

...



