---
- hosts: west, east
  gather_facts: no
  connection: local
  tasks:
  - include_vars: "WanLink.yml"
  - name: Create per-node vars files from Wan-Link data model
    template: src=Generate-HostVars.j2 dest={{inventory_dir}}/host_vars/{{inventory_hostname_short}}.yml

...