---
Customer: Gaffatape
ServiceID: 20
loopbacks: 172.16.1.0/24
OSPFarea: 20
VRF: " vrf Gaffatape-20"

TUNNELS:
- { from: BEL01.east.net, to: IND01.west.net }
- { from: BEL01.east.net, to: SGP01.west.net }
- { from: IND01.west.net, to: SGP01.west.net }

