---
- hosts: all   #"all is the play name"

  tasks:
  - name: Create Folder for results
    file: path={{results_folder}} state=directory
    run_once: true 
  
  - include_tasks: "get_{{platform1|default( ansible_network_os )}}_fact.yml"
  - include_tasks: "get_{{platform2|default('snmp')}}_fact.yml"
  - include_tasks: "report_all_fact_j2.yml"
