---
# This task uses the default connection mechanism of SSH.
- hosts: iosv
  gather_facts: no

  vars:
  - ansible_connection: ssh #Required to override network_cli in config

  tasks:
   - name: get interfaces
     raw: "show ip interface brief"
 