---
- hosts: all   #"all is the play name"

  tasks:
  - name: Create Folder for results
    file: path={{results_folder}} state=directory
    run_once: true 
  - include_tasks: "get_snmp_fact.yml"

################ IOSV #####################
- hosts: iosv
  tasks:
  - include: "get_ios_fact.yml"

################ IOSXR #####################
- hosts: iosxr
  tasks:
  - include: "get_iosxr_fact.yml"

################ Report ####################
- hosts: all  
  tasks:
  - include: "report_all_fact.yml"
