---
all:
 hosts:
 children:
   ios:
    hosts:
     192.168.16.10:
     192.168.16.20:
     192.168.16.30:

   iosxr:
    hosts:
     192.168.16.40:
     192.168.16.50:
     192.168.16.60:

   snmp:
    hosts:
     192.168.16.10:
     192.168.16.20:
     192.168.16.30:
     192.168.16.40:
     192.168.16.50:
     192.168.16.60:      

 vars:
  ansible_become_method: enable
  ansible_network_os: ios
  results_folder: results_files
  report: uptime-version.log
  reportj2: uptime-version-j2.md
  
 
